server:
  port: 8080

spring:
  application:
    name: swiftdrop-backend

  # 1. Cấu hình kết nối PostgreSQL
  datasource:
    url: jdbc:postgresql://localhost:5432/swiftdrop_db
    username: postgres
    password: postgrespassword
    driver-class-name: org.postgresql.Driver

  # 2. Cấu hình JPA & Hibernate
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # 3. Cấu hình Redis
  data:
    redis:
      host: localhost
      port: 6379

  # 4. Cấu hình RabbitMQ
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
